version: 2.0
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:curl
    steps:
      - checkout
      - run:
          name: "upload ftp"
          command: |
            sudo apt-get install -y lftp
            lftp -u "${FTP_USER}","${FTP_PASSWORD}" ftp.studiolegalefavaretto.it -e "set ftp:ssl-allow no; mirror --delete --only-newer --parallel=5 --exclude ".git/" --exclude ".gitignore" --exclude ".travis.yml" --exclude ".circleci/" --exclude "local/" --verbose -R ${CIRCLE_WORKING_DIRECTORY} . ; quit"

